# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: kernel-url:https://github.com/LineageOS/android_kernel_motorola_sm6150.git
          kernel-dir: hanoip 
          kernel-branch: lineage-18.1
          config: hanoip_defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          ksu: true
          ksu-version: main
          android-version: 12
          aosp-clang-version: r383902
          disable-lto: true
          anykernel3: true 
          
    
    
          
